apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobe-{{ default "staging" .Release.Namespace }}-ingress
  namespace: {{ default "staging" .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($apikey_is_ok != 1) {
      return 401;
      }
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - jobe{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}.{{ .Values.dns.name }}
    secretName: tls-secret-jobe-{{ default "staging" .Release.Namespace }}
  rules:
  - host: jobe{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}.{{ .Values.dns.name }}
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: jobeinabox-{{ default "staging" .Release.Namespace }}
            port:
              number: 80
