apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobe
  namespace: {{ default "staging" .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jobe{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}.k8s.cs.calvin.edu
    secretName: tls-secret-jobe-{{ default "staging" .Release.Namespace }}
  rules:
  - host: jobe-{{ default "staging" .Release.Namespace }}{{ .Values.dns.name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jobeinabox
            port:
              name: http
